# NumPy 
Stands for Numerical Python, is a fundamental package for high-performance scientific computing and data analysis in Python. It provides a powerful N-dimensional array object, sophisticated functions, tools for integrating C/C++ and Fortran code, and useful linear algebra, Fourier transform, and random number capabilities.

# Array Creation
Numpy arrays provide a fast and memory-efficient alternative to Python lists. However, the array must be homogeneous (all elements to be of the same data type), while lists can hold elements of varying types.

Arrays in NumPy can be created in multiple ways:

In [1]:
# From Python Lists

import numpy as np

a = np.array([10 ,20, 30]) #Creating one-dimenational array

b = np.array([[1, 2, 3], [4, 5, 6]]) #creating a two-dimentaional array

a,b

(array([10, 20, 30]),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [2]:
# Using builin funcitons

zeros = np.zeros((2, 3)) #creating an arry of zeros: array([[0., 0., 0.], [0., 0., 0.]])

ones = np.ones((2, 1)) #Creating an array of 1 ones: array([[1.], [1.]])

range_array = np.arange(10) #Creating array with range of elements (excluded): array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

identity_matrix = np.eye((3)) #Creating an identity matrix:  array([[1., 0., 0.], [0., 1., 0.], [0., 0., 1.]])


In [3]:
# Create an array filled with a constant value
np.full((2, 2), 7)

array([[7, 7],
       [7, 7]])

In [4]:
# Create an array with evenly spaced elements within a given interval
np.linspace(0, 1, num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [5]:
#Creating array with custom range and steps
range_array_custom = np.arange(2, 8, 2) 
print(list(range_array_custom)) # Arrays can easiby be converted to a list

[2, 4, 6]


# Array Attributes
Key attributes of NumPy arrays include shape, size, and dtype:

In [6]:
a = np.array([[1, 2, 3], [4, 5, 6]])

# Number of array dimensions
print(a.ndim)

# Tuple of array dimensions
print(a.shape)

# Total number of elements in the array
print(a.size)

# Data type of the array elements
print(a.dtype)


2
(2, 3)
6
int64


# Array Manipulation using methods
These methods change the shape, size, or elements of an array.

In [7]:
# Reshape an array
np.arange(6).reshape((3, 2))

array([[0, 1],
       [2, 3],
       [4, 5]])

In [8]:
# Flatten an array
np.array([[1, 2], [3, 4]]).flatten()

array([1, 2, 3, 4])

In [9]:
# Concatenate arrays
np.concatenate([np.array([1, 2]), np.array([3, 4])])

array([1, 2, 3, 4])

In [10]:
# Split an array
np.split(np.array([1, 2, 3, 4]), 2)

[array([1, 2]), array([3, 4])]

In [11]:
# Add a new axis
np.expand_dims(np.array([1, 2]), axis=0)

array([[1, 2]])

In [12]:
arr = np.array([3, 4, 5])

# Add a new axis at the end (transforming it into a column vector)
expanded_arr = np.expand_dims(arr, axis=1)
arr, expanded_arr

(array([3, 4, 5]),
 array([[3],
        [4],
        [5]]))

In [13]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Add a new axis, effectively turning the matrix into a 3D array
expanded_arr_2d = np.expand_dims(arr_2d, axis=0)

expanded_arr_2d.shape, expanded_arr_2d

((1, 2, 3),
 array([[[1, 2, 3],
         [4, 5, 6]]]))

# Indexing and Slicing 
Arrays can be indexed and sliced using square brackets []:

In [14]:
a = np.array([[1, 2, 3], [4, 5, 6]])

# Accessing an element
print(a[0, 1])  # Output: 2

# Slicing a subarray
print(a[1, :])  # Output: [4 5 6]

# Using negative indices
print(a[-1, -2])  # Output: 5

2
[4 5 6]
5


# Array Operations
Arrays support various arithmetic operations, which are applied element-wise:

In [15]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

# Element-wise addition
x + y

array([[ 6,  8],
       [10, 12]])

In [16]:
# Element-wise multiplication
x * y

array([[ 5, 12],
       [21, 32]])

# Broadcasting:

Broadcasting allows NumPy to work with arrays of different shapes when performing arithmetic operations:

In [17]:
x = np.array([[1, 2], [3, 4]])

# Add a scalar to an array
x + 2

array([[3, 4],
       [5, 6]])

In [18]:
# Multiply an array by a scalar
x * 2


array([[2, 4],
       [6, 8]])

# Vectorization: 
Vectorization enables operations to be performed on arrays without explicit loops, which improves performance:

In [19]:
# Calculate the sine of each element
np.sin(x)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ]])

# Advanced Features

# Logic Functions
These functions apply element-wise logic operations:

In [20]:
# Element-wise OR
np.logical_or(np.array([True, False]), np.array([False, True]))

array([ True,  True])

In [21]:
# Element-wise AND
np.logical_and(np.array([True, False]), np.array([False, True]))

array([False, False])

# I/O
NumPy also provides methods to save and load arrays to and from disk.

In [22]:
# Save an array to a binary file in NumPy .npy format
np.save('my_array', np.array([1, 2, 3]))

# Load an array from a .npy file
np.load('my_array.npy')

array([1, 2, 3])

# Mathematical Functions
NumPy provides a comprehensive set of mathematical functions to perform element-wise calculations, linear algebra, etc.

In [23]:
# Element-wise addition
np.add(np.array([1, 2]), np.array([3, 4]))

array([4, 6])

In [24]:
# Matrix multiplication
np.dot(np.array([[1, 2], [3, 4]]), np.array([[5, 6], [7, 8]]))

array([[19, 22],
       [43, 50]])

In [25]:
# Element-wise Exponential
np.exp(np.array([1, 2, 3]))

array([ 2.71828183,  7.3890561 , 20.08553692])

In [26]:
# Element-wise Sine function
np.sin(np.array([0, np.pi/2, np.pi]))

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

# Linear Algebra: 
NumPy provides a set of functions for linear algebra:

In [27]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

#Dot prdouct calculation
print(np.dot(x,y))

[[19 22]
 [43 50]]


In [28]:
#Matrix multiplication
np.matmul(x,y)

array([[19, 22],
       [43, 50]])

In [29]:
#Finding determinent
np.linalg.det(x)

-2.0000000000000004

In [30]:
# Eigenvalues and eigenvectors
np.linalg.eig(np.array([[1, 2], [3, 4]]))

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [31]:
# Inverse of a matrix
np.linalg.inv(np.array([[1, 2], [3, 4]]))

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

# Statistical Methods
Common statistical calculations can be performed with NumPy:

In [32]:
# Mean
print(np.mean(x))

# Standard deviation
print(np.std(x))

# Median
print(np.median(x))

# Sum
print(np.sum(x))

2.5
1.118033988749895
2.5
10


# Boolean Indexing
Arrays can be indexed with boolean expressions:

In [33]:
a = np.array([15, 21, 30, 40, 5, 60])

odds = a[a%2 == 1] #Finding odd elements

greater = a[a>20] #Finding elements greater than 20
odds, greater

(array([15, 21,  5]), array([21, 30, 40, 60]))

# Reshaping and Transposing
Changing the shape and orientation of arrays is commonly needed but does not effect the actual array:


In [34]:
a = np.array([[15, 21, 30],[40, 5, 60]])

# Reshape to convert as a column (total size, 1)
np.reshape(a, (6, 1)) 

array([[15],
       [21],
       [30],
       [40],
       [ 5],
       [60]])

In [35]:
#Reshape just to convert to a row
np.reshape(a, -1)

array([15, 21, 30, 40,  5, 60])

In [36]:
# Transpose
np.transpose(a)

array([[15, 40],
       [21,  5],
       [30, 60]])

# NumPy Arrays vs. Python Lists
When working with numerical data in Python, we often have to choose between lists and NumPy arrays. While both can be used to store collections of values, they serve different purposes and come with distinct features and capabilities.



# Memory Efficiency
NumPy arrays are more memory efficient than Python lists. Arrays store data in a compact, fixed-type format, while lists hold elements as separate objects. Let's compare the memory usage of both:

In [37]:
import numpy as np
import sys

lst = [i for i in range(1000)]
print(f"Size of list: {sys.getsizeof(lst)} bytes")

arr = np.array([i for i in range(1000)])
print(f"Size of NumPy array: {arr.nbytes} bytes")

Size of list: 8856 bytes
Size of NumPy array: 8000 bytes


However, in specific cases using only range() without a loop (if not needed) can improve that memory efficiency for list:

In [38]:
lst = range(1000)
arr = np.arange(1000) # or np.array((range(1000))) prdouce the same result
sys.getsizeof(list), arr.nbytes #or sys.sizeof(arr)

(408, 8000)

# Performance
Most cases NumPy arrays provide faster computation than lists due to their fixed type and contiguous memory allocation. This feature enables efficient access and manipulation of array elements. 

In [39]:
import time
# perforemance: arithmatic operation on a list
start_time = time.time()
list_result = [i+1 for i in lst]
end_time = time.time()
print(f"List manipulation has taken: {end_time - start_time} seconds")
l = end_time - start_time

List manipulation has taken: 9.274482727050781e-05 seconds


In [40]:
# perforemance: same arithmatic operation on a numpy array
start_time = time.time()
arr_result = arr + 1
end_time = time.time()
print(f"Numpy manipulation has taken: {end_time - start_time} seconds")
m = end_time - start_time

Numpy manipulation has taken: 6.508827209472656e-05 seconds


In [41]:
# Or we can use %timeit to find
%timeit list_reult = [i+1 for i in lst]

47.1 µs ± 1.65 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [42]:
%timeit arr_result = arr + 1 

1.05 µs ± 12.8 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


# Functionality
NumPy arrays support a wide range of mathematical and statistical operations out of the box, while lists do not.

In [43]:
# Element-wise addition in lists requires a loop or comprehension
list_sum = [i + j for i, j in zip(lst, lst)]

# Element-wise addition in NumPy arrays is straightforward
array_sum = arr + arr

# Mean of a list requires summing and dividing
list_mean = sum(lst) / len(lst)

# Mean of a NumPy array is a built-in function
array_mean = np.mean(arr)

# Multidimensional Data
While lists can store multidimensional data through nesting, NumPy arrays provide a more intuitive and efficient way to work with such data

In [44]:
# Creating a 2D list (a list of lists)
nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# Accessing an element
print(nested_list[1][2])  # Output: 6

# Modifying an element
nested_list[1][2] = 10
print(nested_list)  # Output: [[1, 2, 3], [4, 5, 10], [7, 8, 9]]

# Iterating over rows and elements
for row in nested_list:
    for element in row:
        print(element, end=' ')
    print()

6
[[1, 2, 3], [4, 5, 10], [7, 8, 9]]
1 2 3 
4 5 10 
7 8 9 


In [45]:
import numpy as np

# Creating a 2D NumPy array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Accessing an element
print(array_2d[1, 2])  # Output: 6

# Modifying an element
array_2d[1, 2] = 10
print(array_2d)
# Output:
# [[ 1  2  3]
#  [ 4  5 10]
#  [ 7  8  9]]

# Iterating over rows and elements
for row in array_2d:
    for element in row:
        print(element, end=' ')
    print()

6
[[ 1  2  3]
 [ 4  5 10]
 [ 7  8  9]]
1 2 3 
4 5 10 
7 8 9 


In [48]:
# NumPy arrays provide the ability to perform more advanced operations easily:

array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Slicing a row or column
print(array_2d[1, :])  # Output: [4 5 6] (second row)
print(array_2d[:, 2])  # Output: [3 6 9] (third column)

# Performing operations on entire rows or columns
print(array_2d[:, 2] + 1)  # Output: [ 4 7 10] (add 1 to each element of the third column)

# Matrix operations
print(array_2d @ array_2d)  # Matrix multiplication


[4 5 6]
[3 6 9]
[ 4  7 10]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
