# PyTorch Debugging
Debugging is an essential aspect of developing machine learning models in PyTorch. PyTorch's dynamic computation graph makes it easier to debug using standard Python debugging tools. 

## Understanding PyTorch's Dynamic Graph
PyTorch uses a dynamic computation graph, meaning the graph is built at runtime. This allows for more interactive debugging and flexibility but requires understanding how PyTorch tracks operations to debug effectively.

# Debugging Techniques

## 1. Using Print Statements

Print tensors and their shapes to understand the flow of data.

In [2]:
import torch
x = torch.randn(5, 3)
print(x)
print(x.shape)

tensor([[ 2.1699, -0.7203,  0.1938],
        [ 0.4552,  1.5074, -0.3009],
        [ 1.9378,  0.2204,  2.0289],
        [ 2.1689, -0.2511,  0.3391],
        [-0.7584,  1.0573,  1.4920]])
torch.Size([5, 3])


## 2. Using Python Debugger
Python debuggers like pdb or integrated development environment (IDE) debuggers.

In [2]:
import torch
import pdb

x = torch.randn(5, 3)
pdb.set_trace()  # Sets a breakpoint
y = x * 2

--Return--
None
> /var/folders/pq/8nvzr_h55nqdlpwmts7fmsq40000gn/T/ipykernel_56734/1260668640.py(5)<module>()
      2 import pdb
      3 
      4 x = torch.randn(5, 3)
----> 5 pdb.set_trace()  # Sets a breakpoint
      6 y = x * 2

--KeyboardInterrupt--

KeyboardInterrupt: Interrupted by user


## 3. Visualizing the Computation Graph

Tools like TensorBoard to visualize the computation graph and track the flow of tensors.


In [ ]:
from torch.utils.tensorboard import SummaryWriter
import torch.nn as nn

writer = SummaryWriter()

model = nn.Sequential(nn.Linear(10, 5), nn.ReLU(), nn.Linear(5, 2))
input_tensor = torch.randn(1, 10)
writer.add_graph(model, input_tensor)
writer.close()


## 4. Checking for NaN and Inf Values

Detect NaN or Inf values in tensors, which can indicate numerical instability.

In [3]:
x = torch.tensor([1.0, float('nan'), float('inf')])
print(torch.isnan(x), torch.isinf(x))


tensor([False,  True, False]) tensor([False, False,  True])


## 5. Using Assertion Statements

Assert conditions to ensure variables have expected values or shapes.
Example:

In [4]:
x = torch.randn(5, 3)
assert x.shape[0] == 5, "Expected 5 rows"

## 6. Gradient Checking

Verify gradients manually to check for correct backpropagation.


In [5]:
x = torch.randn(5, 3, requires_grad = True)
y = x * 2 
y.backward(torch.ones_like(x))
print(x.grad)

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])
